# Generated by Django 4.2.11 on 2026-02-21 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitations.invitation')),
            ],
        ),
    ]
