# Generated by Django 4.2.11 on 2026-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='phone',
        ),
        migrations.AddField(
            model_name='guest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
