# Generated by Django 4.2.11 on 2026-02-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_remove_guest_phone_guest_address_guest_guest_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
