# Generated by Django 4.2.11 on 2026-02-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='akad_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reception_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reception_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='event_date',
            field=models.DateField(),
        ),
    ]
